services:
  dockerweb:
    image: ${DOCKER_REGISTRY-}dockerweb
    build:
      context: .
      dockerfile: DockerWeb/Dockerfile
    environment:
      DOTNET_ENVIRONMENT: Production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockerweb.rule=Host(`uatcrm-docker-xc9icu-ef30cd-31-97-202-93.traefik.me`) && PathPrefix(`/dockerweb`)"
      - "traefik.http.routers.dockerweb.entrypoints=web"
      - "traefik.http.routers.dockerweb.middlewares=strip-dockerweb"
      - "traefik.http.middlewares.strip-dockerweb.stripprefix.prefixes=/dockerweb"
      - "traefik.http.services.dockerweb.loadbalancer.server.port=8080"
    ports:
      - "8081:8080"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
